name: Generate Daily Background

on:
  schedule:
    - cron: "0 7 * * *"   # codziennie o 7:00 UTC
  workflow_dispatch:       # pozwala też uruchomić ręcznie

permissions:
  contents: write

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Generate image with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DATE=$(date +%Y-%m-%d)
          FILE="images/${DATE}.png"
    
          mkdir -p images

          RESPONSE=$(curl -s https://api.openai.com/v1/images/generations \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-image-1",
              "prompt": "World of Tanks battlefield, cinematic style, ultra realistic",
              "size": "1024x1024",
              "n": 1
            }')

          echo $RESPONSE | jq -r '.data[0].b64_json' | base64 --decode > "$FILE"

          echo "Wygenerowany plik: $FILE"
          ls -lh "$FILE"


      - name: Commit new image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add images/
          git commit -m "Add daily background $(date +%Y-%m-%d)" || echo "Brak zmian"
          git push
